language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./gradlew

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p real-deploy
  - mv before-deploy/before-deploy.zip real-deploy/book-aws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-0701-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: real-deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-0701-build
    key: book-aws.zip
    bundle_type: zip
    application: SpringBoot-0701
    deployment_group: SpringBoot-0701
    region: ap-northeast-2
    wait-until-deployed: true

# CI 완료시 메일 알람
notifications:
  email:
    recipients:
      - gitgitwi@gmail.com